baseURL = "https://blog.alphathree.tech/"
languageCode = "en-us"
title = "Alpha3 | Tech Blog - AI-driven solutions for business, creativity, and global impact"
theme = "PaperMod"  
enableInlineShortcodes = true
sitemap = { changefreq = "weekly", priority = 0.5, filename = "sitemap.xml" }

# Add this to your existing config
googleAnalytics = "G-4PJNNJB69Q"  

[outputs]
home = ["HTML", "RSS", "JSON"]  # Add JSON to enable search

[params]
# Theme Parameters
defaultTheme = "dark"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
customCSS = ["css/custom.css"]
customJS = ["js/main.js"]  # Make sure this matches your file path
paginate = 6

# Enable search
enableSearch = true
searchPlaceholder = "Search posts..."

# Configure Fuse.js search options
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 100
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[params.assets]
favicon = "/assets/logo/logo.png"
favicon16x16 = "/assets/logo/logo.png"
favicon32x32 = "/assets/logo/logo.png"

# Home Info Parameters
[params.homeInfoParams]
Title = "Alpha3 Tech Blog"
Content = """
Welcome to Alpha3's official tech blog. Explore our insights, solutions, and innovations.
"""

# SEO Parameters
description = "Alpha3's tech blog provides insights on AI-driven, digital transformation, and technology innovation. Expert articles on software development, cloud architecture, and tech trends."
keywords = ["AI-driven", "digital transformation", "tech blog", "software development", "cloud architecture"]
images = ["/assets/logo/alpha3.jpg"]

# Author Info
[params.author]
name = "Alpha3 Technologies"
image = "/assets/logo/logo.png"

# Open Graph & Twitter Cards
[params.social]
twitter = "@alpha3tech" # Replace with your Twitter handle

# Schema.org
[params.schema]
type = "Organization"
name = "Alpha3 Technologies"
description = "Technology solutions and digital transformation services"
url = "https://alphathree.tech"
logo = "/assets/logo/logo.png"
sameAs = [
    "https://www.linkedin.com/company/alphathree-technologies"
    # Add other social profile URLs
]

# Social Icons
[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/company/alphathree-technologies"

[menu]
[[menu.main]]
identifier = "solutions"
name = "Solutions"
url = "https://alphathree.tech/#solutions"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "https://alphathree.tech/#about"
weight = 2

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "https://blog.alphathree.tech"
weight = 3

[markup.highlight]
noClasses = false
lineNos = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allows HTML in content

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"