backend:
  name: git-gateway
  branch: main  # or "master" if that’s your default branch

media_folder: "static/images/uploads"  # Media files location
public_folder: "/images/uploads"       # Public URL for media

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
